import type { NewsSourcesManifest } from './types'

/**
 * Curated RSS sources manifest for the News module. Each `rsshubPath` is appended to `RSSHUB_BASE_URL`.
 * `subcategory` must match a slug from `news-subcategories.ts` for the source’s `category`.
 *
 * Full manifest RSS checks: `pnpm verify:todo-rsshub` (`scripts/verify-todo-rsshub.mjs` reads this file).
 * `scripts/verify-rsshub-paths.sh` is a smaller curl batch for tech paths only. Routes that returned 503 on your
 * instance are often omitted here until the instance serves them.
 * **v2**: Dropped six `tech-internet` rows that were too narrow for default open pools (see `todo-rsshub-compliance-notes.md`).
 * **v3**: Added RSS_OK sources from `scripts/reports/todo-rsshub-usable-summary.md` that were previously EXTRA-only (social, games, hk_tw, intl).
 * **v4**: `social-platform` / `audio` (播客音频): 小宇宙编辑精选 — pool was empty because no manifest rows used `subcategory: 'audio'`.
 * **v5**: `zhihu-hot-total` moved from `social-platform` / `micro` to `tech-internet` / `developer` — site-wide Zhihu hot
 * skews programming/tech, which dominated the “social micro” merged pool.
 * **v6**: Removed `science-academic` / `health` (医疗健康) list and `medsci-recommend` manifest row.
 * **v7**: Removed `game-entertainment` / `culture` (影视与阅读) list and related manifest rows (film/reading covered by the movie module).
 * **v8**: Removed `social-platform` / `audio` (播客精选) list and `xiaoyuzhou-pickup` manifest row.
 * **v9**: Removed `social-platform` / `micro` (社区热榜精选) list and manifest rows (`weibo-search`, `jianshu-home`, `guangdiu-daily`).
 * **v10**: Removed `tech-internet` / `product` rows `eleduck-posts` (电鸭社区) and `pkmer-recent` (PKMer).
 * **v11**: `zhihu-hot-total` moved from `tech-internet` / `developer` to `general-news` / `headlines` — site-wide hot list is not dev-community scoped.
 * **v12**: Removed `social-platform` category and `video` (视频平台热门) list; dropped `bilibili-popular` (News focuses on text/news RSS).
 * **v13**: Removed `general-news` / `headlines` source `people-headline` (人民网头条); removed `depth` list and sources `infzm-featured`, `caixin-weekly`, `nytimes-morning-briefing`.
 *
 * @returns Manifest object with `version` and `sources` list
 */
export const newsSourcesManifest = {
  version: 13,
  sources: [
    {
      id: 'thepaper',
      label: '澎湃新闻',
      category: 'general-news',
      subcategory: 'headlines',
      region: 'cn',
      rsshubPath: '/thepaper/featured',
      defaultUrl: 'https://www.thepaper.cn',
    },
    {
      id: 'cctv-xwlb',
      label: '央视新闻联播',
      category: 'general-news',
      subcategory: 'headlines',
      region: 'cn',
      rsshubPath: '/cctv/tv/lm/xwlb',
      defaultUrl: 'https://news.cctv.com',
    },
    {
      id: 'huanqiu-china',
      label: '环球网国内',
      category: 'general-news',
      subcategory: 'headlines',
      region: 'cn',
      rsshubPath: '/huanqiu/news/china',
      defaultUrl: 'https://www.huanqiu.com',
    },
    {
      id: 'guancha-redian',
      label: '观察者网热点',
      category: 'general-news',
      subcategory: 'opinion',
      region: 'cn',
      rsshubPath: '/guancha/redian',
      defaultUrl: 'https://www.guancha.cn',
    },
    {
      id: 'jiemian-news',
      label: '界面新闻',
      category: 'general-news',
      subcategory: 'headlines',
      region: 'cn',
      rsshubPath: '/jiemian/lists/801',
      defaultUrl: 'https://www.jiemian.com',
    },
    {
      id: 'chinanews-scroll',
      label: '中国新闻网滚动',
      category: 'general-news',
      subcategory: 'headlines',
      region: 'cn',
      rsshubPath: '/chinanews',
      defaultUrl: 'https://www.chinanews.com.cn',
    },
    {
      id: 'thepaper-pinglun',
      label: '澎湃评论',
      category: 'general-news',
      subcategory: 'opinion',
      region: 'cn',
      rsshubPath: '/thepaper/list/27224',
      defaultUrl: 'https://www.thepaper.cn',
    },
    {
      id: 'eastday-24',
      label: '东方资讯24小时热闻',
      category: 'general-news',
      subcategory: 'headlines',
      region: 'cn',
      rsshubPath: '/eastday/24',
      defaultUrl: 'https://www.eastday.com',
    },
    {
      id: '36kr',
      label: '36氪',
      category: 'tech-internet',
      subcategory: 'media',
      region: 'cn',
      rsshubPath: '/36kr/newsflashes',
      defaultUrl: 'https://www.36kr.com',
    },
    {
      id: 'pingwest-status',
      label: '品玩',
      category: 'tech-internet',
      subcategory: 'media',
      region: 'cn',
      rsshubPath: '/pingwest/status',
      defaultUrl: 'https://www.pingwest.com',
    },
    {
      id: 'ifanr-index',
      label: '爱范儿',
      category: 'tech-internet',
      subcategory: 'media',
      region: 'cn',
      rsshubPath: '/ifanr/index',
      defaultUrl: 'https://www.ifanr.com',
    },
    {
      id: 'cnbeta',
      label: 'cnBeta',
      category: 'tech-internet',
      subcategory: 'media',
      region: 'cn',
      rsshubPath: '/cnbeta',
      defaultUrl: 'https://www.cnbeta.com.tw',
    },
    {
      id: 'mydrivers-hot',
      label: '快科技',
      category: 'tech-internet',
      subcategory: 'media',
      region: 'cn',
      rsshubPath: '/mydrivers/hot',
      defaultUrl: 'https://www.mydrivers.com',
    },
    {
      id: 'solidot',
      label: 'Solidot',
      category: 'tech-internet',
      subcategory: 'developer',
      region: 'cn',
      rsshubPath: '/solidot/www',
      defaultUrl: 'https://www.solidot.org',
    },
    {
      id: 'infoq-recommend',
      label: 'InfoQ 推荐',
      category: 'tech-internet',
      subcategory: 'developer',
      region: 'cn',
      rsshubPath: '/infoq/recommend',
      defaultUrl: 'https://www.infoq.cn',
    },
    {
      id: 'oschina-project',
      label: '开源中国（软件项目）',
      category: 'tech-internet',
      subcategory: 'developer',
      region: 'cn',
      rsshubPath: '/oschina/news/project',
      defaultUrl: 'https://www.oschina.net',
    },
    {
      id: 'oschina-gossip',
      label: '开源中国（资讯）',
      category: 'tech-internet',
      subcategory: 'developer',
      region: 'cn',
      rsshubPath: '/oschina/news/gossip',
      defaultUrl: 'https://www.oschina.net',
    },
    {
      id: 'csdn-geeknews',
      label: 'CSDN 极客头条',
      category: 'tech-internet',
      subcategory: 'developer',
      region: 'cn',
      rsshubPath: '/csdn/blog/csdngeeknews',
      defaultUrl: 'https://blog.csdn.net',
    },
    {
      id: 'v2ex-hot',
      label: 'V2EX',
      category: 'tech-internet',
      subcategory: 'developer',
      region: 'cn',
      rsshubPath: '/v2ex/topics/hot',
      defaultUrl: 'https://www.v2ex.com',
    },
    {
      id: 'sspai',
      label: '少数派',
      category: 'tech-internet',
      subcategory: 'product',
      region: 'cn',
      rsshubPath: '/sspai/index',
      defaultUrl: 'https://sspai.com',
    },
    {
      id: 'woshipm-popular',
      label: '人人都是产品经理',
      category: 'tech-internet',
      subcategory: 'product',
      region: 'cn',
      rsshubPath: '/woshipm/popular/daily',
      defaultUrl: 'https://www.woshipm.com',
    },
    {
      id: 'xiaoheihe',
      label: '小黑盒',
      category: 'game-entertainment',
      subcategory: 'games',
      region: 'cn',
      rsshubPath: '/xiaoheihe/news',
      defaultUrl: 'https://www.xiaoheihe.cn',
    },
    {
      id: 'guokr',
      label: '果壳科学人',
      category: 'science-academic',
      subcategory: 'stem',
      region: 'cn',
      rsshubPath: '/guokr/scientific',
      defaultUrl: 'https://www.guokr.com',
    },
    {
      id: 'sciencenet',
      label: '科学网精选博客',
      category: 'science-academic',
      subcategory: 'stem',
      region: 'cn',
      /** RSSHub: `lib/routes/sciencenet/blog.ts` official example `/sciencenet/blog` — there is no `/sciencenet/news` upstream. */
      rsshubPath: '/sciencenet/blog',
      defaultUrl: 'https://blog.sciencenet.cn',
    },
    {
      id: 'zhihu-hot-total',
      label: '知乎热榜',
      /** Full-site trending topics; merged with general headlines, not the dev/tech-community list. */
      category: 'general-news',
      subcategory: 'headlines',
      region: 'cn',
      rsshubPath: '/zhihu/hot/total',
      defaultUrl: 'https://www.zhihu.com',
    },
    {
      id: 'gamersky-news',
      label: '游民星空',
      category: 'game-entertainment',
      subcategory: 'games',
      region: 'cn',
      rsshubPath: '/gamersky/news',
      defaultUrl: 'https://www.gamersky.com',
    },
    {
      id: 'gcores-news',
      label: '机核资讯',
      category: 'game-entertainment',
      subcategory: 'games',
      region: 'cn',
      rsshubPath: '/gcores/news',
      defaultUrl: 'https://www.gcores.com',
    },
    {
      id: 'ali213-news',
      label: '游侠网',
      category: 'game-entertainment',
      subcategory: 'games',
      region: 'cn',
      rsshubPath: '/ali213/news',
      defaultUrl: 'https://www.ali213.net',
    },
    {
      id: 'tgbus-news',
      label: '电玩巴士',
      category: 'game-entertainment',
      subcategory: 'games',
      region: 'cn',
      rsshubPath: '/tgbus/list/news',
      defaultUrl: 'https://www.tgbus.com',
    },
    {
      id: 'indienova-article',
      label: 'indienova',
      category: 'game-entertainment',
      subcategory: 'games',
      region: 'cn',
      rsshubPath: '/indienova/article',
      defaultUrl: 'https://www.indienova.cn',
    },
    {
      id: 'ccf-news',
      label: '中国计算机学会',
      category: 'science-academic',
      subcategory: 'stem',
      region: 'cn',
      rsshubPath: '/ccf/news',
      defaultUrl: 'https://www.ccf.org.cn',
    },
    {
      id: 'zaobao-realtime-china',
      label: '联合早报（即时·中港台）',
      category: 'general-news',
      subcategory: 'headlines',
      region: 'hk_tw',
      rsshubPath: '/zaobao/realtime/china',
      defaultUrl: 'https://www.zaobao.com.sg',
    },
    {
      id: 'zaobao-znews-china',
      label: '联合早报（中国新闻）',
      category: 'general-news',
      subcategory: 'headlines',
      region: 'hk_tw',
      rsshubPath: '/zaobao/znews/china',
      defaultUrl: 'https://www.zaobao.com.sg',
    },
    {
      id: 'cna-aall',
      label: '中央社 CNA',
      category: 'general-news',
      subcategory: 'headlines',
      region: 'hk_tw',
      rsshubPath: '/cna/aall',
      defaultUrl: 'https://www.cna.com.tw',
    },
    {
      id: 'ithome-tw-news',
      label: 'iThome 台湾',
      category: 'tech-internet',
      subcategory: 'media',
      region: 'hk_tw',
      rsshubPath: '/ithome/tw/feeds/news',
      defaultUrl: 'https://www.ithome.com.tw',
    },
    {
      id: 'bbc-world',
      label: 'BBC World',
      category: 'general-news',
      subcategory: 'headlines',
      region: 'intl',
      rsshubPath: '/bbc/world',
      defaultUrl: 'https://www.bbc.com',
    },
    {
      id: 'bbc-chinese',
      label: 'BBC 中文网',
      category: 'general-news',
      subcategory: 'headlines',
      region: 'intl',
      rsshubPath: '/bbc/chinese',
      defaultUrl: 'https://www.bbc.com/zhongwen',
    },
    {
      id: 'techcrunch-news',
      label: 'TechCrunch',
      category: 'tech-internet',
      subcategory: 'media',
      region: 'intl',
      rsshubPath: '/techcrunch/news',
      defaultUrl: 'https://techcrunch.com',
    },
    {
      id: 'nasa-apod',
      label: 'NASA APOD',
      category: 'science-academic',
      subcategory: 'stem',
      region: 'intl',
      rsshubPath: '/nasa/apod',
      defaultUrl: 'https://apod.nasa.gov',
    },
    {
      id: 'nature-news',
      label: 'Nature News',
      category: 'science-academic',
      subcategory: 'stem',
      region: 'intl',
      rsshubPath: '/nature/news',
      defaultUrl: 'https://www.nature.com',
    },
  ],
} satisfies NewsSourcesManifest
