import type { NewsSourcesManifest } from './types'

/**
 * Curated RSS sources manifest for the News module. Each `rsshubPath` is appended to `RSSHUB_BASE_URL`.
 * @returns Manifest object with `version` and `sources` list
 */
export const newsSourcesManifest = {
  version: 1,
  sources: [
    {
      id: 'thepaper',
      label: '澎湃新闻',
      category: 'general-news',
      region: 'cn',
      rsshubPath: '/thepaper/featured',
      defaultUrl: 'https://www.thepaper.cn',
    },
    {
      id: 'cctv-xwlb',
      label: '央视新闻联播',
      category: 'general-news',
      region: 'cn',
      rsshubPath: '/cctv/tv/lm/xwlb',
      defaultUrl: 'https://news.cctv.com',
    },
    {
      id: 'people-headline',
      label: '人民网头条',
      category: 'general-news',
      region: 'cn',
      rsshubPath: '/people',
      defaultUrl: 'http://people.com.cn',
    },
    {
      id: 'huanqiu-china',
      label: '环球网国内',
      category: 'general-news',
      region: 'cn',
      rsshubPath: '/huanqiu/news/china',
      defaultUrl: 'https://www.huanqiu.com',
    },
    {
      id: 'guancha-redian',
      label: '观察者网热点',
      category: 'general-news',
      region: 'cn',
      rsshubPath: '/guancha/redian',
      defaultUrl: 'https://www.guancha.cn',
    },
    {
      id: 'cankaoxiaoxi-diyi',
      label: '参考消息第一关注',
      category: 'general-news',
      region: 'cn',
      rsshubPath: '/cankaoxiaoxi/diyi',
      defaultUrl: 'http://www.cankaoxiaoxi.com',
    },
    {
      id: 'sina-roll-guonei',
      label: '新浪滚动国内',
      category: 'general-news',
      region: 'cn',
      rsshubPath: '/sina/rollnews/2510',
      defaultUrl: 'https://news.sina.com.cn',
    },
    {
      id: 'jiemian-news',
      label: '界面新闻',
      category: 'general-news',
      region: 'cn',
      rsshubPath: '/jiemian/lists/801',
      defaultUrl: 'https://www.jiemian.com',
    },
    {
      id: 'chinanews-scroll',
      label: '中国新闻网滚动',
      category: 'general-news',
      region: 'cn',
      rsshubPath: '/chinanews',
      defaultUrl: 'https://www.chinanews.com.cn',
    },
    {
      id: 'infzm-featured',
      label: '南方周末推荐',
      category: 'general-news',
      region: 'cn',
      rsshubPath: '/infzm/1',
      defaultUrl: 'https://www.infzm.com',
    },
    {
      id: 'eastday-24',
      label: '东方资讯24小时热闻',
      category: 'general-news',
      region: 'cn',
      rsshubPath: '/eastday/24',
      defaultUrl: 'https://www.eastday.com',
    },
    {
      id: '36kr',
      label: '36氪',
      category: 'tech-internet',
      region: 'cn',
      rsshubPath: '/36kr/newsflashes',
      defaultUrl: 'https://www.36kr.com',
    },
    {
      id: 'sspai',
      label: '少数派',
      category: 'tech-internet',
      region: 'cn',
      rsshubPath: '/sspai/index',
      defaultUrl: 'https://sspai.com',
    },
    {
      id: 'solidot',
      label: 'Solidot',
      category: 'tech-internet',
      region: 'cn',
      rsshubPath: '/solidot/www',
      defaultUrl: 'https://www.solidot.org',
    },
    {
      id: 'bilibili-popular',
      label: '哔哩哔哩热门',
      category: 'social-platform',
      region: 'cn',
      rsshubPath: '/bilibili/popular/all',
      defaultUrl: 'https://www.bilibili.com',
    },
    {
      id: 'weibo-search',
      label: '微博热搜',
      category: 'social-platform',
      region: 'cn',
      rsshubPath: '/weibo/search/hot',
      defaultUrl: 'https://weibo.com',
    },
    {
      id: 'xiaoheihe',
      label: '小黑盒',
      category: 'game-entertainment',
      region: 'cn',
      rsshubPath: '/xiaoheihe/news',
      defaultUrl: 'https://www.xiaoheihe.cn',
    },
    {
      id: 'guokr',
      label: '果壳科学人',
      category: 'science-academic',
      region: 'cn',
      rsshubPath: '/guokr/scientific',
      defaultUrl: 'https://www.guokr.com',
    },
    {
      id: 'sciencenet',
      label: '科学网',
      category: 'science-academic',
      region: 'cn',
      rsshubPath: '/sciencenet/news',
      defaultUrl: 'https://www.sciencenet.cn',
    },
  ],
} satisfies NewsSourcesManifest
