export { getCachedFuelPrice, getCachedProvinceFuelPrice, getFuelPrice } from './api'
export type { RechargePromoResult } from './promo'
export { calcRechargePromo } from './promo'
export type { FuelPrice, FuelPriceData, FuelPriceHistory, FuelPriceList, ProvinceFuelPrice } from './types'
export { isFuelPrice, isFuelPriceData, isFuelPriceList } from './types'
